volumes:
  ps-elasticsearch1:
networks:
  ps-elasticsearch:
services:
  elasticsearch-node1:
    image: localhost/ps-elasticsearch
    container_name: elasticsearch
    environment:
      - 'CLUSTER_NAME=demo'
      - 'NODE_NAME=ps-elasticsearch'
      - discovery.type=single-node
      # - INITIAL_MASTER_NODES=elasticsearch-node1
      # - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - 'ELASTICSEARCH_JAVA_OPTS=-Xms1g -Xmx1g'
    volumes:
      - ps-elasticsearch1:/data:Z
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - ps-elasticsearch