#
# ---------------------------------- Cluster -----------------------------------
#
cluster:
  name: ${CLUSTER_NAME}
  initial_master_nodes: ${INITIAL_MASTER_NODES}

#
# ------------------------------------ Node ------------------------------------
#
node:
  name: ${NODE_NAME}
  # master: ${NODE_MASTER}
  # data: ${NODE_DATA}

#
# ------------------------------------ Path ------------------------------------
#
path:
  data: /data/data
  logs: /data/log

#
# ----------------------------------- Memory -----------------------------------
#
bootstrap:
  memory_lock: true

#
# ---------------------------------- Network -----------------------------------
#
network:
  host: ${NETWORK_HOST}

http:
  type: OrclNetty4HttpServerTransport
  port: ${HTTP_PORT}
  # enabled: ${HTTP_ENABLE}
  compression: true
  max_content_length: 512mb
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

#
# --------------------------------- Discovery ----------------------------------
#
discovery:
  # seed_hosts: ["127.0.0.1", "[::1]"]
  type: single-node

#
# ---------------------------------- SSL/TLS ----------------------------------
#
# When the PeopleSoft callback url is https, install the Peoplesoft Root CA
# certificate in Elasticsearch truststore.
#
orclssl:
  http:
    ssl: false
  transport:
    ssl: false
  callback: ${CALLBACK_SSL}

#
#--------------------------------Transport-------------------------------------
#
transport:
  type: OrclNetty4Transport

# Misc
orcl.kibana.sessionTimeOut: 86400000
script.painless.regex.enabled: true
